### ISSUE TITLE
Exception thrown by runner.py on startup

### ISSUE THREAD

**Issue by RosalesJ** [yurikhan/kitty-grab#1]
Thanks for this kitten. It adds a great missing feature to kitty.

## Issue
Exception is thrown directly after triggering the hotkey for the grab action.

```
Unhandled exception running kitten:
Traceback (most recent call last):
  File "kitty/runner.py", line 142, in main
  File "kitty/runner.py", line 68, in launch
TypeError: main() takes 0 positional arguments but 1 was given
Press Enter to quit...
```

## System
kitty 0.12.3

## Replicate
Minimal user configuration in kitty.conf:
```
map ctrl+space kitten grab1.py
```

**Comment by yurikhan** [comment]
This kitten uses the new feature, kittens without UI, introduced in Kitty 0.13.0. (The first stage has no UI, it takes the current window’s title, cursor and scroll position, and passes them to the second stage.)

I should probably document the version requirement more clearly.
