### ISSUE TITLE
Copy/paste not working

### ISSUE THREAD

**Issue by sdfux** [yurikhan/kitty-grab#27]
I just installed kitty_grab but is not working

-Press mapped key
-Kitty flashes
-Change title to "grab"
-Select text
-Press enter
-But when trying to paste, it paste what is already on de clipboard no the selection I just made.

`$ kitty -v  
kitty 0.27.1 created by Kovid Goyal
`
Windows system X11

**Comment by sdfux** [comment]
Hi Yurikhan,

Yes, `Ctrl+Shift+c` works fine.
Yes, after pressing `Enter` it change back from "Grab"
No error output on copy/paste, after opening kitty from other terminal the only I get is this:
    `ignoreboth or ignorespace present in bash HISTCONTROL setting, showing running command in window title will not be robust`
but no errors in any of the steps described above.

**Comment by sdfux** [comment]
I did an ls -ltr
And after selecting the last row and pressing `Enter` this is what I get

`{'copy': '-rw-r--r-- 1 gabo gabo 25400 Apr 10 10:52 _grab_ui.py'}`

**Comment by yurikhan** [comment]
So basically the correct data gets almost to the end of kitty_grab and up to the kitty’s API function to set clipboard contents, but that last step does not work for some reason.

Last ditch attempt, does it work for you if you change it this way?

```py
def handle_result(args: List[str], result: 'ResultDict',
                  target_window_id: WindowId, boss: Boss) -> None:
    if 'copy' in result:
        boss.clipboard.set_text(result['copy'])
```

**Comment by sdfux** [comment]
Sadly, no.

**Comment by yurikhan** [comment]
Does it work for you in past versions of Kitty? What is the last version that works?

(It works for me on v0.26.5, and building v0.27.1 requires(?) Go 1.20 which is not packaged for Ubuntu 22.04, and I’m reluctant to install bleeding edge, so I can’t check easily.)

**Comment by sdfux** [comment]
Sorry, I used to use urxvt, but I was recommended to try kitty, and this is something I use a lot on urxvt.

Let me check if I find how to install the 0.26.5 version and I will let you know.

**Comment by sdfux** [comment]
I already installed 0.26.5 but still not working

Running kitty from another terminal I get this

```[100 12:28:42.767600] Ignoring unknown config key: undercurl_style
[100 12:28:42.768541] Ignoring unknown config key: show_hyperlink_targets
[100 12:28:42.770935] Ignoring unknown config key: tab_title_max_length
[100 12:28:42.771572] Ignoring unknown config key: background_tint_gaps
ignoreboth or ignorespace present in bash HISTCONTROL setting, showing running command in window title will not be robust
```

**Comment by kovidgoyal** [comment]
Although I have to ask why is copy_string_to_clipbaord being used at all? Shouldn't this kitten just be passing the text to kitty to copy via OSC 52?

**Comment by yurikhan** [comment]
@kovidgoyal What are the advantages and disadvantages of the two approaches? As far as I can see:

OSC 52:

* (+) stable API
* (­­­−) possibly length-limited
* (−) gated by `clipboard_control write-clipboard`
* (0) works over SSH but that’s not relevant because kittens run locally

calling a method:

* (+) slightly faster as it avoids a base64 encode/decode and protocol parse

**Comment by yurikhan** [comment]
@sdfux Please try the [`osc52`](https://github.com/yurikhan/kitty_grab/tree/osc52) branch.

**Comment by kovidgoyal** [comment]
That's more or less correct, the main reason I asked is that I assume
this kitten is running as a child process reading the screen contents on
stdin. In such a scenario its just easier to use OSC52 in the child
process itself, this allows for instance copying multiple things without
quitting the child process.

**Comment by sdfux** [comment]
Hi all, 
I'm using the `osc52` branch, and it is working now.

Thanks for your help and sorry for the late response since when the comments arrive it was 2am here were I live.

**Comment by pallaswept** [comment]
I also had a failure to copy. It worked fine so long as I never went past the top of the screen into the scrollback buffer.

OSC52 branch is working as far as copy and paste goes, although it does something weird with the highlighted text.:

![image](https://github.com/yurikhan/kitty_grab/assets/132128962/751b8ddb-aa28-4c02-984d-c369650e5465)

I'm using kitty especially because of its OSC52 support which is needed for copyQ on wayland.

**Comment by yurikhan** [comment]
I think weird behavior in presence of tab characters is a separate bug (#28).

**Comment by pallaswept** [comment]
> I think weird behavior in presence of tab characters is a separate bug (#28).

🤦 I didn't even notice, of course it is the tabs. Sorry, I should have opened a separate case. My bad, and thank you for helping :)

**Comment by pallaswept** [comment]
> I think weird behavior in presence of tab characters is a separate bug (#28).

🤦 I didn't even notice, of course it is the tabs. Sorry, I should have opened a separate case. My bad, and thank you for helping :)
